### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhouxingfako** [chaitin/xapp#1]
mac m1的电脑，用xapp_darwin_amd64 跑。
plugin 也下载到~/.xray/xapp/plugins目录下了。执行报错

 ./xapp_darwin_amd64 -h
  __  /\    ___.   /\_.   /\_.
  | |/ /   /   |  / __.\ / __.\
  |   /XRAY™/| | / /_/ // /_/ /
 /   |   / ___ |/ .___// .___/  
/ /|_|  / /  |_/_/    /_/      
\/v0.0.1\/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1021892]

goroutine 1 [running]:
io/fs.ReadDir({0x267bc60, 0x3635600}, {0x23d3551, 0x7})
	io/fs/readdir.go:44 +0x224
io/fs.walkDir({0x267bc60, 0x3635600}, {0x23d3551, 0x7}, {0x268bee8, 0xc0007531a0}, 0xc0007142c8)
	io/fs/walk.go:81 +0x12d
io/fs.WalkDir({0x267bc60, 0x3635600}, {0x23d3551, 0x7}, 0xc0007142c8)
	io/fs/walk.go:122 +0xd2
git.in.chaitin.net/lohengrin/xraykit/loader/gamma.(*Loader).LoadBuiltin.func1()
	git.in.chaitin.net/lohengrin/xraykit/loader/gamma/loader_gamma.go:116 +0x125
sync.(*Once).doSlow(0xa0?, 0x2307560?)
	sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	sync/once.go:65
git.in.chaitin.net/lohengrin/xraykit/loader/gamma.(*Loader).LoadBuiltin(0x35fc8e0?)
	git.in.chaitin.net/lohengrin/xraykit/loader/gamma/loader_gamma.go:110 +0x45
git.in.chaitin.net/lohengrin/xraykit/xray.MultiLoader.LoadBuiltin({0xc000753160?, 0x1, 0x14?})
	git.in.chaitin.net/lohengrin/xraykit/xray/loader.go:160 +0xbf
git.in.chaitin.net/lohengrin/xraykit/xray/cli.(*App).LoadAllPlugins(0xc00069f6c0)
	git.in.chaitin.net/lohengrin/xraykit/xray/cli/app.go:548 +0x364
git.in.chaitin.net/lohengrin/xraykit/xray/cli.(*App).generateConfig(0xc000829fb0?, {0x0, 0x0, 0x23ddd53?})
	git.in.chaitin.net/lohengrin/xraykit/xray/cli/app.go:300 +0x32
git.in.chaitin.net/lohengrin/xraykit/xray/cli.(*App).prepareConfigFile(0xc00069f6c0, {0x0, 0x0, 0x0})
	git.in.chaitin.net/lohengrin/xraykit/xray/cli/app.go:429 +0x17a
git.in.chaitin.net/lohengrin/xraykit/xray/cli.(*App).Cli(0xc00069f6c0, {0xc0001ca000, 0x2, 0x2})
	git.in.chaitin.net/lohengrin/xraykit/xray/cli/app.go:192 +0x44c
git.in.chaitin.net/lohengrin/xraykit/xray/cli.(*App).Run(0xc00069f520, {0x268ba50, 0x3635600}, {0xc0001ca000, 0x2, 0x2})
	git.in.chaitin.net/lohengrin/xraykit/xray/cli/app.go:59 +0xe8
main.main()
	git.in.chaitin.net/lohengrin/xraykit/cli/xapp/xapp.go:116 +0x1ff

**Comment by Jarcis-cy** [comment]
试试新版本，应该修了
